### ISSUE TITLE
Failed to activate the project-banner package: Atom V1.37.0 x64 Linux

### ISSUE THREAD

**Issue by igoryonya** [elis/project-banner#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [project-banner](https://github.com/elis/project-banner) package 0.3.3

### Stack Trace

Failed to activate the project-banner package

```
At watch undefined/package.json ENOENT

Error: watch undefined/package.json ENOENT
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1386:19)
    at Object.fs.watch (fs.js:1412:11)
    at Object.watchConfig (/packages/project-banner/lib/reader.js:48:22)
    at /packages/project-banner/lib/project-banner-view.js:54:35)
    at Object.activate (/packages/project-banner/lib/project-banner.js:29:29)
    at Package.activateNow (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:3385948)
    at measure (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:3385360)
    at Package.measure (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:3382991)
    at activationPromise.activationPromise.Promise (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:3385220)
    at new Promise (<anonymous>)
    at Package.activate (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:3385163)
    at PackageManager.activatePackage (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:382600)
    at config.transactAsync (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:382216)
    at Config.transactAsync (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:332386)
    at PackageManager.activatePackages (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:382166)
    at PackageManager.activate (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:11:381784)
    at t.loadState.then (/snap/atom/227/usr/share/atom/resources/app/static/<embedded>:1:707960)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
add-cursors 0.2.2 
atom-abbreviation 2.5.0 
atom-beautify 0.33.4 
atom-code-music 3.0.2 
atom-css-unit-converter 1.1.1 
atom-referenceseeker 0.6.0 
atom-translator 0.3.0 
atom-unsaved-changes 0.4.0 
atom-wrap-in-tag 0.6.0 
auto-indent 0.5.0 
break-time 0.3.1 
browser-plus 0.0.98 
busy-signal 2.0.1 
camel-select 0.1.3 
caniuse-css 1.1.5 
chrome-color-picker 0.8.0 
code-champion 1.0.0 
code-peek 1.4.21 
code-shadow 0.1.0 
color-indent 1.0.2 
color-picker 2.3.0 
copy-highlighted 0.5.0 
corporate-gibberish 0.4.0 
css-comb 2.5.0 
css-hyperclick 0.1.5 
css-specificity 0.2.2 
css-spy 0.6.0 
cursor-indicator 1.3.0 
cute-cursor 0.5.0 
dictator 0.2.0 
double-tag 1.7.0 
drag-drop-text 0.1.4 
eject-selection 0.1.0 
emmet 2.4.3 
expand-region 0.4.2 
expand-selection-to-indentation 0.4.0 
expand-selection-to-quotes 0.11.0 
file-watcher 2.0.0 
find-selection 0.16.0 
fix-indent-on-paste 0.1.1 
folded-code-preview 0.2.5 
git-log 0.4.1 
git-projects 1.17.0 
git-time-machine 2.1.0 
git-time-metric 1.1.8 
graphviz-preview-plus 1.5.9 
gutter-shadow 1.1.0 
highlight-bad-chars 2.0.0 
highlight-selected 0.16.0 
html-to-css 0.2.2 
indent-guide-improved 1.4.13 
indentation-jumper 0.1.2 
intentions 1.1.5 
invert-selection 1.0.0 
irc 0.4.0 
itimetrack 5.0.9 
japanese-word-selection 0.5.1 
Java-Bytecode-Disassembler 0.12.6 
key-peek 0.2.12 
language-dot 1.7.0 
linter 2.3.0 
linter-perl 0.9.0 
linter-perl-lint 0.1.2 
linter-ui-default 1.7.1 
magical-selection 2.0.3 
math-selection 0.3.0 
multirow-tabs 0.3.3 
native-color-picker 0.2.5 
neon-cursor 1.6.0 
nyan-indent 0.9.8 
one-theme-color-by-project 2.0.0 
organized 0.8.1 
outline-selection 0.3.2 
payment-time 1.0.0 
project-banner 0.3.3 
project-plus 1.0.0 
pseudo-synthesizer 0.5.1 
quick-highlight 0.13.0 
rainbow-selection 0.3.2 
rainbow-selection-flux 1.2.0 
RebelChat 0.8.1 
recognizer 0.3.0 
reindent 1.5.0 
reverse-selection 0.2.0 
sane-indentation 1.0.8 
scroll-percentage 1.3.0 
scroll-searcher 5.2.0 
scroll-without-moving-cursor 0.3.5 
selection-counter 1.0.1 
selection-highlight 0.1.6 
selector-to-tag 0.5.0 
self-closing-tag 0.2.1 
simplified-russian-menu 1.3.0 
split-selection-into-cursors 0.2.0 
stacked-tabs 0.1.3 
stash-tabs 0.1.0 
state-machine-cat-preview 4.5.4 
svg-preview 0.14.0 
swap-selection 0.4.0 
tag 0.5.0 
technobabble 0.4.0 
tree-view-autoresize 2.3.0 
tree-view-git-branch 0.1.2 
var-that-color 0.2.2 
```

**Comment by spouki** [comment]
Hello !
sorry for the unexpected up of this thread (without giving you a fix).

I got the same error on windows 7 (64bits), and I thought it would be interesting to get another source of data about this issue (on a different platform) :

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [project-banner](https://github.com/elis/project-banner) package 0.3.3


### Stack Trace

Failed to activate the project-banner package

```
At ENOENT: no such file or directory, watch 'undefined/package.json'

Error: ENOENT: no such file or directory, watch 'undefined/package.json'
    at FSWatcher.start (fs.js:1426:26)
    at Object.fs.watch (fs.js:1467:11)
    at Object.watchConfig (/packages/project-banner/lib/reader.js:48:22)
    at /packages/project-banner/lib/project-banner-view.js:54:35)
    at Object.activate (/packages/project-banner/lib/project-banner.js:29:29)
    at Package.activateNow (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3541396)
    at measure (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540808)
    at Package.measure (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3538418)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540668)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540611)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381612)
    at config.transactAsync (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381228)
    at Config.transactAsync (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:331162)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381178)
    at PackageManager.activate (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:380728)
    at t.loadState.then (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:1:734978)
```

### Commands

```
     -0:15.7.0 line-ending-selector:convert-to-LF (atom-text-editor.editor)
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-csv-markdown 1.0.2 
atom-html-templates 0.1.3 
atom-ide-ui 0.13.0 
background-tips-fortune-literature 0.29.0 
busy-signal 2.0.1 
file-icons 2.1.33 
folder-treasure-boxes 2.2.0 
force-line-endings 0.1.1 
git-split-diff-hyperclick 0.3.12 
go-debug 1.6.2 
go-plus 6.1.0 
go-postfix 0.3.0 
go-signature-statusbar 1.2.3 
go-tip 2.4.0 
hyperclick 0.0.0 
intentions 1.1.5 
language-batchfile 0.7.5 
linter 2.3.0 
linter-golinter 1.3.0 
linter-ui-default 1.7.1 
lp-snippets 0.0.27 
minimap 4.29.9 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-lens 0.2.0 
my-script-pusher undefined 
ncoda-structureview 0.1.0 
nyan-indent 0.9.8 
platformio-ide-terminal 2.9.1 
pretty-json 2.1.2 
project-banner 0.3.3 
python-black 0.7.0 
rainbow-csv 0.3.1 
split-diff 1.6.0 
todo-show 2.3.2 
vk-terminal 3.0.1 
```

Yours,
spouki

**Comment by spouki** [comment]
I have a fix (temporary)
At line 54 in project-banner/lib/project-banner-view.js 
replace 

`this.subscriptions.add(Reader.watchConfig(Reader.packageFile, this.packgeJsonUpdated))`

by 

`try  {
      this.subscriptions.add(Reader.watchConfig(Reader.packageFile, this.packgeJsonUpdated))
    } catch(error) {
      console.log("ERROR")
      throw new Error('Fuck')
    }`

It is only a workaround for testing and debugging, but need to get a real fix.

@elis 

Why this fix ?
Because the problem encountered is that the lib does not test wether there is a .bannerfile.json/cson, hence this leads to a break.

But as I had only my experience and the one from igoryonya , I only rely on these for my explanation of this bug+fix.

Maybe I'm wrong, but I don"t have any other source for comparing.

Yours,
spouki

**Comment by Scaenicus** [comment]
I can confirm that this error occurs everytime you open a project without package.json and/or bannerfile
It also occurs when opening a new empty window.

**Comment by KontrivedMedia** [comment]
Are there any instructions that walk you through how to set this up properly as the README is confusing.

**Comment by KontrivedMedia** [comment]
@elis can you give an example of what a package.json looks like please.
